// frontend-angular-app/src/app/components/reference-manager-dialog/reference-manager-dialog.component.ts
import { CommonModule } from '@angular/common';
import { Component, DestroyRef, Inject, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatTableModule } from '@angular/material/table';
import { firstValueFrom } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ApiError } from '../../core/http/api-error';
import { CompanyType } from '../../core/models/company-type';
import { Genre } from '../../core/models/genre';
import { MediaOutlet } from '../../core/models/media-outlet';
import { ProductionCompany } from '../../core/models/production-company';
import { CompanyTypeService } from '../../core/services/company-type.service';
import { GenreService } from '../../core/services/genre.service';
import { MediaOutletService } from '../../core/services/media-outlet.service';
import { ProductionCompanyService } from '../../core/services/production-company.service';
import { fetchAllPageContent } from '../../core/utils/fetch-all-page-content';

export type ReferenceEntityType = 'genres' | 'production-companies' | 'media-outlets';

export interface ReferenceManagerDialogData {
  entityType: ReferenceEntityType;
}

@Component({
  selector: 'app-reference-manager-dialog',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    MatButtonModule,
    MatDialogModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
    MatTableModule,
  ],
  templateUrl: './reference-manager-dialog.component.html',
  styleUrl: './reference-manager-dialog.component.scss',
})
export class ReferenceManagerDialogComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly genreService = inject(GenreService);
  private readonly companyService = inject(ProductionCompanyService);
  private readonly mediaOutletService = inject(MediaOutletService);
  private readonly companyTypeService = inject(CompanyTypeService);
  private readonly dialogRef = inject(MatDialogRef<ReferenceManagerDialogComponent>);
  private readonly destroyRef = inject(DestroyRef);

  readonly entityType: ReferenceEntityType;

  rows: Array<Genre | ProductionCompany | MediaOutlet> = [];
  companyTypes: CompanyType[] = [];
  loading = false;
  submitting = false;
  error: string | null = null;
  search = '';
  editingId: number | null = null;
  changed = false;

  readonly form = this.fb.group({
    name: this.fb.control<string>('', [Validators.required]),
    websiteUrl: this.fb.control<string>(''),
    foundedYear: this.fb.control<number | null>(null),
    ceo: this.fb.control<string>(''),
    companyTypeId: this.fb.control<number | null>(null),
  });

  constructor(@Inject(MAT_DIALOG_DATA) data: ReferenceManagerDialogData) {
    this.entityType = data.entityType;
  }

  ngOnInit(): void {
    this.dialogRef
      .backdropClick()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe(() => this.close());
    this.dialogRef
      .keydownEvents()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((event) => {
        if (event.key === 'Escape') {
          this.close();
        }
      });
    this.loadCompanyTypes();
    this.loadRows();
  }

  get label(): string {
    switch (this.entityType) {
      case 'genres':
        return 'Genres';
      case 'production-companies':
        return 'Production companies';
      case 'media-outlets':
        return 'Media outlets';
      default:
        return 'Reference data';
    }
  }

  get displayedColumns(): string[] {
    if (this.entityType === 'genres') {
      return ['id', 'name', 'actions'];
    }

    if (this.entityType === 'production-companies') {
      return ['id', 'name', 'websiteUrl', 'foundedYear', 'ceo', 'companyType', 'actions'];
    }

    return ['id', 'name', 'websiteUrl', 'foundedYear', 'actions'];
  }

  get filteredRows() {
    const query = this.search.trim().toLowerCase();
    if (!query) {
      return this.rows;
    }

    return this.rows.filter((row) => {
      const name = row.name?.toLowerCase?.() || '';
      const website = (row as MediaOutlet | ProductionCompany).websiteUrl?.toLowerCase?.() || '';
      const ceo = (row as ProductionCompany).ceo?.toLowerCase?.() || '';
      return name.includes(query) || website.includes(query) || ceo.includes(query);
    });
  }

  async loadCompanyTypes() {
    if (this.entityType !== 'production-companies') {
      this.companyTypes = [];
      return;
    }

    try {
      const response = await firstValueFrom(this.companyTypeService.getAll());
      this.companyTypes = Array.isArray(response) ? response : [];
    } catch {
      this.companyTypes = [];
    }
  }

  async loadRows() {
    try {
      this.loading = true;
      this.error = null;

      if (this.entityType === 'genres') {
        const response = await firstValueFrom(this.genreService.getAll());
        this.rows = Array.isArray(response) ? response : [];
        return;
      }

      if (this.entityType === 'production-companies') {
        this.rows = await fetchAllPageContent((params) => this.companyService.getAll(params), {
          sortBy: 'name',
          sortDirection: 'ASC' as const,
        });
        return;
      }

      this.rows = await fetchAllPageContent((params) => this.mediaOutletService.getAll(params), {
        sortBy: 'name',
        sortDirection: 'ASC' as const,
      });
    } catch (error) {
      const apiError = error as ApiError;
      this.error = apiError?.message || 'Failed to load data.';
    } finally {
      this.loading = false;
    }
  }

  resetForm() {
    this.editingId = null;
    this.form.reset({
      name: '',
      websiteUrl: '',
      foundedYear: null,
      ceo: '',
      companyTypeId: null,
    });
  }

  editRow(row: Genre | ProductionCompany | MediaOutlet) {
    this.editingId = row.id ?? null;

    if (this.entityType === 'genres') {
      this.form.patchValue({ name: row.name || '' });
      return;
    }

    if (this.entityType === 'media-outlets') {
      const outlet = row as MediaOutlet;
      this.form.patchValue({
        name: outlet.name || '',
        websiteUrl: outlet.websiteUrl || '',
        foundedYear: outlet.foundedYear ?? null,
      });
      return;
    }

    const company = row as ProductionCompany;
    this.form.patchValue({
      name: company.name || '',
      websiteUrl: company.websiteUrl || '',
      foundedYear: company.foundedYear ?? null,
      ceo: company.ceo || '',
      companyTypeId: (company as ProductionCompany & { companyTypeId?: number }).companyTypeId ?? null,
    });
  }

  private buildPayload() {
    const value = this.form.getRawValue();

    if (this.entityType === 'genres') {
      return { name: value.name?.trim() || '' };
    }

    if (this.entityType === 'media-outlets') {
      return {
        name: value.name?.trim() || '',
        websiteUrl: value.websiteUrl?.trim() || null,
        foundedYear: value.foundedYear ?? null,
      };
    }

    return {
      name: value.name?.trim() || '',
      websiteUrl: value.websiteUrl?.trim() || null,
      foundedYear: value.foundedYear ?? null,
      ceo: value.ceo?.trim() || null,
      companyTypeId: value.companyTypeId ?? null,
    };
  }

  private validateForm(): boolean {
    if (!this.form.value.name?.trim()) {
      this.error = 'Name is required.';
      return false;
    }

    if (this.entityType !== 'genres') {
      const foundedYear = this.form.value.foundedYear;
      if (foundedYear !== null && foundedYear !== undefined && foundedYear < 1900) {
        this.error = 'Founded year must be at least 1900.';
        return false;
      }
    }

    this.error = null;
    return true;
  }

  async submit() {
    if (!this.validateForm()) {
      return;
    }

    try {
      this.submitting = true;
      const payload = this.buildPayload();

      if (this.entityType === 'genres') {
        if (this.editingId) {
          await firstValueFrom(this.genreService.update(this.editingId, payload));
        } else {
          await firstValueFrom(this.genreService.create(payload));
        }
      }

      if (this.entityType === 'production-companies') {
        if (this.editingId) {
          await firstValueFrom(this.companyService.update(this.editingId, payload));
        } else {
          await firstValueFrom(this.companyService.create(payload));
        }
      }

      if (this.entityType === 'media-outlets') {
        if (this.editingId) {
          await firstValueFrom(this.mediaOutletService.update(this.editingId, payload));
        } else {
          await firstValueFrom(this.mediaOutletService.create(payload));
        }
      }

      await this.loadRows();
      this.resetForm();
      this.changed = true;
    } catch (error) {
      const apiError = error as ApiError;
      this.error = apiError?.message || 'Failed to save record.';
    } finally {
      this.submitting = false;
    }
  }

  async deleteRow(row: Genre | ProductionCompany | MediaOutlet) {
    const confirmed = window.confirm(`Delete "${row.name}"?`);
    if (!confirmed || !row.id) {
      return;
    }

    try {
      this.submitting = true;
      if (this.entityType === 'genres') {
        await firstValueFrom(this.genreService.delete(row.id));
      }

      if (this.entityType === 'production-companies') {
        await firstValueFrom(this.companyService.delete(row.id));
      }

      if (this.entityType === 'media-outlets') {
        await firstValueFrom(this.mediaOutletService.delete(row.id));
      }

      await this.loadRows();
      this.changed = true;
    } catch (error) {
      const apiError = error as ApiError;
      this.error = apiError?.message || 'Failed to delete record.';
    } finally {
      this.submitting = false;
    }
  }

  close() {
    this.dialogRef.close({ changed: this.changed });
  }
}

<h2 mat-dialog-title>{{ label }} manager</h2>

<mat-dialog-content class="dialog-content">
  <div *ngIf="error" class="error-banner">
    <mat-icon color="warn">error_outline</mat-icon>
    <span>{{ error }}</span>
  </div>

  <section class="form-card">
    <h3>{{ editingId ? 'Edit record' : 'Create record' }}</h3>

    <div class="form-grid">
      <mat-form-field appearance="outline" class="full">
        <mat-label>Name</mat-label>
        <input matInput [formControl]="form.controls.name" />
      </mat-form-field>

      <mat-form-field *ngIf="entityType !== 'genres'" appearance="outline">
        <mat-label>Website URL</mat-label>
        <input matInput [formControl]="form.controls.websiteUrl" />
      </mat-form-field>

      <mat-form-field *ngIf="entityType !== 'genres'" appearance="outline">
        <mat-label>Founded year</mat-label>
        <input matInput type="number" min="1900" [formControl]="form.controls.foundedYear" />
      </mat-form-field>

      <mat-form-field *ngIf="entityType === 'production-companies'" appearance="outline">
        <mat-label>CEO</mat-label>
        <input matInput [formControl]="form.controls.ceo" />
      </mat-form-field>

      <mat-form-field *ngIf="entityType === 'production-companies'" appearance="outline">
        <mat-label>Company type</mat-label>
        <mat-select [formControl]="form.controls.companyTypeId">
          <mat-option [value]="null">None</mat-option>
          <mat-option *ngFor="let companyType of companyTypes" [value]="companyType.id">
            {{ companyType.name }}
          </mat-option>
        </mat-select>
      </mat-form-field>
    </div>

    <div class="form-actions">
      <button mat-flat-button color="primary" (click)="submit()" [disabled]="submitting">
        {{ editingId ? 'Save' : 'Create' }}
      </button>
      <button mat-stroked-button color="primary" *ngIf="editingId" (click)="resetForm()" [disabled]="submitting">
        Cancel edit
      </button>
    </div>
  </section>

  <section class="table-controls">
    <mat-form-field appearance="outline" class="full">
      <mat-label>Search</mat-label>
      <input matInput [(ngModel)]="search" />
    </mat-form-field>
    <button mat-stroked-button color="primary" (click)="loadRows()" [disabled]="loading">
      Refresh
    </button>
  </section>

  <div *ngIf="loading" class="loading-row">Loading...</div>

  <table mat-table [dataSource]="filteredRows" class="reference-table" *ngIf="!loading">
    <ng-container matColumnDef="id">
      <th mat-header-cell *matHeaderCellDef>ID</th>
      <td mat-cell *matCellDef="let row">{{ row.id }}</td>
    </ng-container>

    <ng-container matColumnDef="name">
      <th mat-header-cell *matHeaderCellDef>Name</th>
      <td mat-cell *matCellDef="let row">{{ row.name }}</td>
    </ng-container>

    <ng-container matColumnDef="websiteUrl" *ngIf="entityType !== 'genres'">
      <th mat-header-cell *matHeaderCellDef>Website</th>
      <td mat-cell *matCellDef="let row">{{ row.websiteUrl || '-' }}</td>
    </ng-container>

    <ng-container matColumnDef="foundedYear" *ngIf="entityType !== 'genres'">
      <th mat-header-cell *matHeaderCellDef>Founded</th>
      <td mat-cell *matCellDef="let row">{{ row.foundedYear || '-' }}</td>
    </ng-container>

    <ng-container matColumnDef="ceo" *ngIf="entityType === 'production-companies'">
      <th mat-header-cell *matHeaderCellDef>CEO</th>
      <td mat-cell *matCellDef="let row">{{ row.ceo || '-' }}</td>
    </ng-container>

    <ng-container matColumnDef="companyType" *ngIf="entityType === 'production-companies'">
      <th mat-header-cell *matHeaderCellDef>Company type</th>
      <td mat-cell *matCellDef="let row">{{ row.companyTypeName || '-' }}</td>
    </ng-container>

    <ng-container matColumnDef="actions">
      <th mat-header-cell *matHeaderCellDef>Actions</th>
      <td mat-cell *matCellDef="let row">
        <button mat-icon-button (click)="editRow(row)">
          <mat-icon>edit</mat-icon>
        </button>
        <button mat-icon-button color="warn" (click)="deleteRow(row)">
          <mat-icon>delete</mat-icon>
        </button>
      </td>
    </ng-container>

    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>

  <div class="empty-state" *ngIf="!loading && filteredRows.length === 0">
    No records found.
  </div>
</mat-dialog-content>

<mat-dialog-actions align="end">
  <button mat-button (click)="close()">Close</button>
</mat-dialog-actions>

// frontend-react-app/src/components/reference/ReferenceManagerDialog.jsx
﻿import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import {
  Alert,
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  IconButton,
  InputLabel,
  MenuItem,
  Paper,
  Select,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Typography,
} from '@mui/material';
import { useCallback, useEffect, useMemo, useState } from 'react';
import CompanyTypeService from '../../services/CompanyTypeService';
import GenreService from '../../services/GenreService';
import log from '../../services/Logger';
import MediaOutletService from '../../services/MediaOutletService';
import ProductionCompanyService from '../../services/ProductionCompanyService';
import { fetchAllPageContent } from '../../utils/fetchAllPageContent';

const ENTITY_TYPES = Object.freeze({
  GENRES: 'genres',
  PRODUCTION_COMPANIES: 'production-companies',
  MEDIA_OUTLETS: 'media-outlets',
});

const getEntityLabel = (entityType) => {
  if (entityType === ENTITY_TYPES.GENRES) {
    return 'Genres';
  }

  if (entityType === ENTITY_TYPES.PRODUCTION_COMPANIES) {
    return 'Production companies';
  }

  if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
    return 'Media outlets';
  }

  return 'Reference data';
};

const getDefaultFormValues = (entityType) => {
  if (entityType === ENTITY_TYPES.GENRES) {
    return { name: '' };
  }

  if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
    return { name: '', websiteUrl: '', foundedYear: '' };
  }

  return { name: '', foundedYear: '', websiteUrl: '', ceo: '', companyTypeId: '' };
};

const toNullableNumber = (value) => {
  if (value === '' || value === null || value === undefined) {
    return null;
  }

  const parsed = Number(value);
  return Number.isNaN(parsed) ? null : parsed;
};

function ReferenceManagerDialog({
  open,
  entityType,
  onClose,
  onChanged,
}) {
  const [rows, setRows] = useState([]);
  const [companyTypes, setCompanyTypes] = useState([]);
  const [loading, setLoading] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState(null);
  const [search, setSearch] = useState('');
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(getDefaultFormValues(entityType));

  const isEditing = editingId !== null;
  const label = getEntityLabel(entityType);

  const resetForm = useCallback(() => {
    setEditingId(null);
    setForm(getDefaultFormValues(entityType));
  }, [entityType]);

  const loadRows = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);

      if (entityType === ENTITY_TYPES.GENRES) {
        const response = await GenreService.getAll();
        setRows(Array.isArray(response.data) ? response.data : []);
        return;
      }

      if (entityType === ENTITY_TYPES.PRODUCTION_COMPANIES) {
        const allCompanies = await fetchAllPageContent(
          (params) => ProductionCompanyService.getAll(params),
          {
            sortBy: 'name',
            sortDirection: 'ASC',
          }
        );
        setRows(allCompanies);
        return;
      }

      if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
        const allOutlets = await fetchAllPageContent(
          (params) => MediaOutletService.getAll(params),
          {
            sortBy: 'name',
            sortDirection: 'ASC',
          }
        );
        setRows(allOutlets);
      }
    } catch (loadError) {
      log.error('Failed to load reference rows:', loadError);
      setError(loadError.message || 'Failed to load data.');
    } finally {
      setLoading(false);
    }
  }, [entityType]);

  const loadCompanyTypes = useCallback(async () => {
    if (entityType !== ENTITY_TYPES.PRODUCTION_COMPANIES) {
      setCompanyTypes([]);
      return;
    }

    try {
      const response = await CompanyTypeService.getAll();
      setCompanyTypes(Array.isArray(response.data) ? response.data : []);
    } catch (loadError) {
      log.warn('Failed to load company types:', loadError);
      setCompanyTypes([]);
    }
  }, [entityType]);

  useEffect(() => {
    if (!open) {
      return;
    }

    setSearch('');
    resetForm();
    loadCompanyTypes();
    loadRows();
  }, [loadCompanyTypes, loadRows, open, resetForm]);

  const filteredRows = useMemo(() => {
    const normalizedSearch = search.trim().toLowerCase();
    if (!normalizedSearch) {
      return rows;
    }

    return rows.filter((item) => {
      const name = item.name?.toLowerCase() || '';
      const website = item.websiteUrl?.toLowerCase() || '';
      const ceo = item.ceo?.toLowerCase() || '';
      return (
        name.includes(normalizedSearch) ||
        website.includes(normalizedSearch) ||
        ceo.includes(normalizedSearch)
      );
    });
  }, [rows, search]);

  const emptyStateColSpan = useMemo(() => {
    if (entityType === ENTITY_TYPES.GENRES) {
      return 3;
    }

    if (entityType === ENTITY_TYPES.PRODUCTION_COMPANIES) {
      return 7;
    }

    return 5;
  }, [entityType]);

  const handleFieldChange = (fieldName) => (event) => {
    setForm((prev) => ({ ...prev, [fieldName]: event.target.value }));
  };

  const handleEdit = (row) => {
    setEditingId(row.id);

    if (entityType === ENTITY_TYPES.GENRES) {
      setForm({ name: row.name || '' });
      return;
    }

    if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
      setForm({
        name: row.name || '',
        websiteUrl: row.websiteUrl || '',
        foundedYear: row.foundedYear ?? '',
      });
      return;
    }

    setForm({
      name: row.name || '',
      foundedYear: row.foundedYear ?? '',
      websiteUrl: row.websiteUrl || '',
      ceo: row.ceo || '',
      companyTypeId: row.companyTypeId ?? '',
    });
  };

  const buildPayload = () => {
    if (entityType === ENTITY_TYPES.GENRES) {
      return { name: form.name.trim() };
    }

    if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
      return {
        name: form.name.trim(),
        websiteUrl: form.websiteUrl?.trim() || null,
        foundedYear: toNullableNumber(form.foundedYear),
      };
    }

    return {
      name: form.name.trim(),
      foundedYear: toNullableNumber(form.foundedYear),
      websiteUrl: form.websiteUrl?.trim() || null,
      ceo: form.ceo?.trim() || null,
      companyTypeId: toNullableNumber(form.companyTypeId),
    };
  };

  const validateForm = () => {
    if (!form.name?.trim()) {
      setError('Name is required.');
      return false;
    }

    if (entityType !== ENTITY_TYPES.GENRES) {
      const foundedYear = toNullableNumber(form.foundedYear);
      if (foundedYear !== null && foundedYear < 1900) {
        setError('Founded year must be at least 1900.');
        return false;
      }
    }

    setError(null);
    return true;
  };

  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    try {
      setSubmitting(true);
      const payload = buildPayload();

      if (entityType === ENTITY_TYPES.GENRES) {
        if (isEditing) {
          await GenreService.update(editingId, payload);
        } else {
          await GenreService.create(payload);
        }
      }

      if (entityType === ENTITY_TYPES.PRODUCTION_COMPANIES) {
        if (isEditing) {
          await ProductionCompanyService.update(editingId, payload);
        } else {
          await ProductionCompanyService.create(payload);
        }
      }

      if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
        if (isEditing) {
          await MediaOutletService.update(editingId, payload);
        } else {
          await MediaOutletService.create(payload);
        }
      }

      await loadRows();
      resetForm();
      if (onChanged) {
        onChanged();
      }
    } catch (submitError) {
      log.error('Failed to submit reference form:', submitError);
      setError(submitError.message || 'Failed to save record.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (rowId, rowName) => {
    const confirmed = window.confirm(`Delete "${rowName}"?`);
    if (!confirmed) {
      return;
    }

    try {
      setSubmitting(true);
      setError(null);

      if (entityType === ENTITY_TYPES.GENRES) {
        await GenreService.delete(rowId);
      }

      if (entityType === ENTITY_TYPES.PRODUCTION_COMPANIES) {
        await ProductionCompanyService.delete(rowId);
      }

      if (entityType === ENTITY_TYPES.MEDIA_OUTLETS) {
        await MediaOutletService.delete(rowId);
      }

      await loadRows();
      if (onChanged) {
        onChanged();
      }
    } catch (deleteError) {
      log.error('Failed to delete reference row:', deleteError);
      setError(deleteError.message || 'Failed to delete record.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="lg">
      <DialogTitle>{label} manager</DialogTitle>
      <DialogContent dividers>
        <Stack spacing={2}>
          {error && <Alert severity="error">{error}</Alert>}

          <Paper variant="outlined" sx={{ p: 2 }}>
            <Stack spacing={2}>
              <Typography variant="h6">
                {isEditing ? 'Edit record' : 'Create record'}
              </Typography>

              <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                <TextField
                  label="Name"
                  value={form.name || ''}
                  onChange={handleFieldChange('name')}
                  required
                  fullWidth
                />

                {entityType !== ENTITY_TYPES.GENRES && (
                  <TextField
                    label="Website URL"
                    value={form.websiteUrl || ''}
                    onChange={handleFieldChange('websiteUrl')}
                    fullWidth
                  />
                )}

                {entityType !== ENTITY_TYPES.GENRES && (
                  <TextField
                    label="Founded year"
                    type="number"
                    value={form.foundedYear ?? ''}
                    onChange={handleFieldChange('foundedYear')}
                    slotProps={{ htmlInput: { min: 1900 } }}
                    sx={{ minWidth: 150 }}
                  />
                )}

                {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && (
                  <TextField
                    label="CEO"
                    value={form.ceo || ''}
                    onChange={handleFieldChange('ceo')}
                    sx={{ minWidth: 180 }}
                  />
                )}

                {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && (
                  <FormControl sx={{ minWidth: 180 }}>
                    <InputLabel id="company-type-select-label">Company type</InputLabel>
                    <Select
                      labelId="company-type-select-label"
                      label="Company type"
                      value={form.companyTypeId ?? ''}
                      onChange={handleFieldChange('companyTypeId')}
                    >
                      <MenuItem value="">None</MenuItem>
                      {companyTypes.map((companyType) => (
                        <MenuItem key={companyType.id} value={companyType.id}>
                          {companyType.name}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                )}
              </Stack>

              <Stack direction="row" spacing={1}>
                <Button
                  variant="contained"
                  onClick={handleSubmit}
                  disabled={submitting}
                >
                  {isEditing ? 'Save' : 'Create'}
                </Button>
                {isEditing && (
                  <Button variant="outlined" onClick={resetForm} disabled={submitting}>
                    Cancel edit
                  </Button>
                )}
              </Stack>
            </Stack>
          </Paper>

          <Stack direction={{ xs: 'column', md: 'row' }} spacing={1}>
            <TextField
              label="Search"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              fullWidth
            />
            <Button
              variant="outlined"
              startIcon={<RefreshRoundedIcon />}
              onClick={loadRows}
              disabled={loading}
            >
              Refresh
            </Button>
          </Stack>

          <TableContainer component={Paper} variant="outlined">
            <Table size="small">
              <TableHead>
                <TableRow>
                  <TableCell>ID</TableCell>
                  <TableCell>Name</TableCell>
                  {entityType !== ENTITY_TYPES.GENRES && <TableCell>Website</TableCell>}
                  {entityType !== ENTITY_TYPES.GENRES && <TableCell>Founded</TableCell>}
                  {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && <TableCell>CEO</TableCell>}
                  {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && <TableCell>Company type</TableCell>}
                  <TableCell align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {filteredRows.map((row) => (
                  <TableRow key={row.id}>
                    <TableCell>{row.id}</TableCell>
                    <TableCell>{row.name}</TableCell>
                    {entityType !== ENTITY_TYPES.GENRES && <TableCell>{row.websiteUrl || '-'}</TableCell>}
                    {entityType !== ENTITY_TYPES.GENRES && <TableCell>{row.foundedYear || '-'}</TableCell>}
                    {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && <TableCell>{row.ceo || '-'}</TableCell>}
                    {entityType === ENTITY_TYPES.PRODUCTION_COMPANIES && <TableCell>{row.companyTypeName || '-'}</TableCell>}
                    <TableCell align="right">
                      <IconButton size="small" onClick={() => handleEdit(row)}>
                        <EditRoundedIcon fontSize="small" />
                      </IconButton>
                      <IconButton
                        size="small"
                        color="error"
                        onClick={() => handleDelete(row.id, row.name)}
                      >
                        <DeleteOutlineRoundedIcon fontSize="small" />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
                {filteredRows.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={emptyStateColSpan}>
                      <Typography color="text.secondary" variant="body2">
                        No records found.
                      </Typography>
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Close</Button>
      </DialogActions>
    </Dialog>
  );
}

export default ReferenceManagerDialog;
