// frontend-angular-app/src/app/pages/game-details-page/game-details-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ApiError } from '../../core/http/api-error';
import { GameDetail } from '../../core/models/game';
import { GameService } from '../../core/services/game.service';

@Component({
  selector: 'app-game-details-page',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatCardModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatTableModule,
    RouterLink,
  ],
  templateUrl: './game-details-page.component.html',
  styleUrl: './game-details-page.component.scss',
})
export class GameDetailsPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly gameService = inject(GameService);

  game: GameDetail | null = null;
  loading = true;
  error: string | null = null;
  deleting = false;

  readonly requirementColumns = [
    'type',
    'storageGb',
    'ramGb',
    'cpuGhz',
    'gpuTflops',
    'vramGb',
  ];

  ngOnInit(): void {
    this.loadGame();
  }

  async loadGame(): Promise<void> {
    const id = this.route.snapshot.paramMap.get('id');
    if (!id) {
      this.error = 'Game ID is missing.';
      this.loading = false;
      return;
    }

    try {
      this.loading = true;
      this.error = null;
      this.game = await firstValueFrom(this.gameService.getById(id));
    } catch (error) {
      const apiError = error as ApiError;
      this.error = apiError?.message || 'Failed to load game details.';
    } finally {
      this.loading = false;
    }
  }

  async deleteGame(): Promise<void> {
    if (!this.game?.id) {
      return;
    }

    const confirmed = window.confirm('Delete this game? This action cannot be undone.');
    if (!confirmed) {
      return;
    }

    try {
      this.deleting = true;
      await firstValueFrom(this.gameService.delete(this.game.id));
      this.router.navigate(['/']);
    } catch (error) {
      const apiError = error as ApiError;
      this.error = apiError?.message || 'Failed to delete game.';
    } finally {
      this.deleting = false;
    }
  }
}

<section class="page">
  <mat-card *ngIf="loading" class="state">
    <mat-progress-spinner mode="indeterminate"></mat-progress-spinner>
  </mat-card>

  <mat-card *ngIf="error" class="state error-state">
    <mat-icon color="warn">error_outline</mat-icon>
    <span>{{ error }}</span>
    <div class="state-actions">
      <button mat-flat-button color="primary" (click)="loadGame()">Retry</button>
      <button mat-stroked-button color="primary" routerLink="/">Back to Games</button>
    </div>
  </mat-card>

  <ng-container *ngIf="!loading && !error && game">
    <div class="page-header">
      <div>
        <h1>{{ game.title }}</h1>
        <p>Release year: {{ game.releaseYear || '-' }}</p>
        <p class="rating">
          <mat-icon>star</mat-icon>
          <span *ngIf="game.averageRating !== null && game.averageRating !== undefined; else noRating">
            {{ game.averageRating | number: '1.0-0' }}/100
          </span>
          <ng-template #noRating>Rating: N/A</ng-template>
        </p>
      </div>
      <div class="header-actions">
        <button mat-stroked-button color="primary" routerLink="/">Back</button>
        <button mat-stroked-button color="primary" [routerLink]="['/games', game.id, 'edit']">Edit</button>
        <button mat-flat-button color="warn" (click)="deleteGame()" [disabled]="deleting">Delete</button>
      </div>
    </div>

    <mat-card class="section-card">
      <h2>About</h2>
      <p class="muted">{{ game.description || 'No description provided.' }}</p>
      <p class="muted">Developer: {{ game.developer?.name || '-' }}</p>
      <p class="muted">Publisher: {{ game.publisher?.name || '-' }}</p>
      <mat-chip-set>
        <mat-chip *ngFor="let genre of game.genres" variant="outlined">{{ genre.name }}</mat-chip>
      </mat-chip-set>
    </mat-card>

    <mat-card class="section-card">
      <div class="section-header">
        <h2>System Requirements</h2>
        <button mat-stroked-button color="primary" disabled>
          <mat-icon>add_circle_outline</mat-icon>
          Add requirement
        </button>
      </div>

      <div *ngIf="!game.systemRequirements.length" class="empty-state">No system requirements added yet.</div>

      <table mat-table [dataSource]="game.systemRequirements" *ngIf="game.systemRequirements.length">
        <ng-container matColumnDef="type">
          <th mat-header-cell *matHeaderCellDef>Type</th>
          <td mat-cell *matCellDef="let row">{{ row.type?.name || '-' }}</td>
        </ng-container>

        <ng-container matColumnDef="storageGb">
          <th mat-header-cell *matHeaderCellDef>Storage (GB)</th>
          <td mat-cell *matCellDef="let row">{{ row.storageGb ?? '-' }}</td>
        </ng-container>

        <ng-container matColumnDef="ramGb">
          <th mat-header-cell *matHeaderCellDef>RAM (GB)</th>
          <td mat-cell *matCellDef="let row">{{ row.ramGb ?? '-' }}</td>
        </ng-container>

        <ng-container matColumnDef="cpuGhz">
          <th mat-header-cell *matHeaderCellDef>CPU (GHz)</th>
          <td mat-cell *matCellDef="let row">{{ row.cpuGhz ?? '-' }}</td>
        </ng-container>

        <ng-container matColumnDef="gpuTflops">
          <th mat-header-cell *matHeaderCellDef>GPU (TFLOPS)</th>
          <td mat-cell *matCellDef="let row">{{ row.gpuTflops ?? '-' }}</td>
        </ng-container>

        <ng-container matColumnDef="vramGb">
          <th mat-header-cell *matHeaderCellDef>VRAM (GB)</th>
          <td mat-cell *matCellDef="let row">{{ row.vramGb ?? '-' }}</td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="requirementColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: requirementColumns"></tr>
      </table>
    </mat-card>

    <mat-card class="section-card">
      <div class="section-header">
        <h2>Reviews</h2>
        <button mat-stroked-button color="primary" disabled>
          <mat-icon>add_circle_outline</mat-icon>
          Add review
        </button>
      </div>

      <div *ngIf="!game.reviews.length" class="empty-state">No reviews added yet.</div>

      <div class="review-grid" *ngIf="game.reviews.length">
        <mat-card *ngFor="let review of game.reviews" class="review-card">
          <h3>{{ review.mediaOutlet?.name || 'Unknown outlet' }}</h3>
          <p class="muted">Score: {{ review.score ?? '-' }}</p>
          <p class="muted">{{ review.summary || 'No summary.' }}</p>
        </mat-card>
      </div>
    </mat-card>
  </ng-container>
</section>

// frontend-react-app/src/pages/GameDetailsPage.jsx
﻿import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded';
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Paper,
  Rating,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import { useCallback, useEffect, useState } from 'react';
import { Link as RouterLink, useNavigate, useParams } from 'react-router-dom';
import GameService from '../services/GameService';
import log from '../services/Logger';

function GameDetailsPage() {
  const { id } = useParams();
  const navigate = useNavigate();

  const [game, setGame] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [deleting, setDeleting] = useState(false);

  const loadGame = useCallback(async () => {
    if (!id) {
      setError('Game ID is missing.');
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      const response = await GameService.getById(id);
      setGame(response.data);
      setError(null);
    } catch (loadError) {
      log.error('Failed to load game details:', loadError);
      setError(loadError.message || 'Failed to load game details.');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadGame();
  }, [loadGame]);

  const handleDelete = async () => {
    if (!id) {
      return;
    }

    const confirmed = window.confirm('Delete this game? This action cannot be undone.');
    if (!confirmed) {
      return;
    }

    try {
      setDeleting(true);
      await GameService.delete(id);
      navigate('/');
    } catch (deleteError) {
      log.error('Failed to delete game:', deleteError);
      setError(deleteError.message || 'Failed to delete game.');
    } finally {
      setDeleting(false);
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" mt={10}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Stack spacing={2}>
        <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
          Game Details
        </Typography>
        <Alert severity="error">{error}</Alert>
        <Stack direction="row" spacing={1}>
          <Button variant="contained" startIcon={<RefreshRoundedIcon />} onClick={loadGame}>
            Retry
          </Button>
          <Button component={RouterLink} to="/" variant="outlined" startIcon={<ArrowBackRoundedIcon />}>
            Back to Games
          </Button>
        </Stack>
      </Stack>
    );
  }

  if (!game) {
    return (
      <Stack spacing={2}>
        <Alert severity="info">Game was not found.</Alert>
        <Button component={RouterLink} to="/" variant="outlined" startIcon={<ArrowBackRoundedIcon />}>
          Back to Games
        </Button>
      </Stack>
    );
  }

  return (
    <Stack spacing={3}>
      <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ md: 'flex-start' }} spacing={2}>
        <Box>
          <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
            {game.title}
          </Typography>
          <Typography color="text.secondary">
            Release year: {game.releaseYear || '-'}
          </Typography>
          <Box mt={1} display="flex" alignItems="center" gap={1}>
            {game.averageRating !== null && game.averageRating !== undefined ? (
              <>
                <Rating value={game.averageRating / 20} readOnly precision={0.5} size="small" />
                <Typography variant="body2" color="text.secondary">
                  {Math.round(game.averageRating)}/100
                </Typography>
              </>
            ) : (
              <Typography variant="body2" color="text.secondary">Rating: N/A</Typography>
            )}
          </Box>
        </Box>

        <Stack direction="row" spacing={1}>
          <Button component={RouterLink} to="/" variant="outlined" startIcon={<ArrowBackRoundedIcon />}>
            Back
          </Button>
          <Button
            component={RouterLink}
            to={`/games/${game.id}/edit`}
            variant="outlined"
            startIcon={<EditRoundedIcon />}
          >
            Edit
          </Button>
          <Button
            variant="contained"
            color="error"
            startIcon={<DeleteOutlineRoundedIcon />}
            onClick={handleDelete}
            disabled={deleting}
          >
            Delete
          </Button>
        </Stack>
      </Stack>

      <Paper sx={{ p: 2.5 }}>
        <Stack spacing={1.5}>
          <Typography variant="h6">About</Typography>
          <Typography color="text.secondary">
            {game.description || 'No description provided.'}
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Developer: {game.developer?.name || '-'}
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Publisher: {game.publisher?.name || '-'}
          </Typography>
          <Box display="flex" gap={1} flexWrap="wrap">
            {(game.genres || []).map((genre) => (
              <Chip key={genre.id} label={genre.name} variant="outlined" />
            ))}
          </Box>
        </Stack>
      </Paper>

      <Paper sx={{ p: 2.5 }}>
        <Stack spacing={1.5}>
          <Typography variant="h6">System Requirements</Typography>
          {(game.systemRequirements || []).length === 0 ? (
            <Alert severity="info">No system requirements added yet.</Alert>
          ) : (
            <TableContainer>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Type</TableCell>
                    <TableCell>Storage (GB)</TableCell>
                    <TableCell>RAM (GB)</TableCell>
                    <TableCell>CPU (GHz)</TableCell>
                    <TableCell>GPU (TFLOPS)</TableCell>
                    <TableCell>VRAM (GB)</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {game.systemRequirements.map((item) => (
                    <TableRow key={item.id}>
                      <TableCell>{item.type?.name || '-'}</TableCell>
                      <TableCell>{item.storageGb ?? '-'}</TableCell>
                      <TableCell>{item.ramGb ?? '-'}</TableCell>
                      <TableCell>{item.cpuGhz ?? '-'}</TableCell>
                      <TableCell>{item.gpuTflops ?? '-'}</TableCell>
                      <TableCell>{item.vramGb ?? '-'}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </Stack>
      </Paper>

      <Paper sx={{ p: 2.5 }}>
        <Stack spacing={1.5}>
          <Typography variant="h6">Reviews</Typography>
          {(game.reviews || []).length === 0 ? (
            <Alert severity="info">No reviews added yet.</Alert>
          ) : (
            <Stack spacing={1.5}>
              {game.reviews.map((review) => (
                <Card key={review.id} variant="outlined">
                  <CardContent>
                    <Stack spacing={1}>
                      <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
                        {review.mediaOutlet?.name || 'Unknown outlet'}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        Score: {review.score ?? '-'}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        {review.summary || 'No summary.'}
                      </Typography>
                    </Stack>
                  </CardContent>
                </Card>
              ))}
            </Stack>
          )}
        </Stack>
      </Paper>
    </Stack>
  );
}

export default GameDetailsPage;
