// frontend-angular-app/src/app/pages/game-form-page/game-form-page.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, DestroyRef, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { ActivatedRoute, Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ApiError } from '../../core/http/api-error';
import { GameService } from '../../core/services/game.service';
import { GenreService } from '../../core/services/genre.service';
import { ProductionCompanyService } from '../../core/services/production-company.service';
import { Genre } from '../../core/models/genre';
import { ProductionCompany } from '../../core/models/production-company';
import { fetchAllPageContent } from '../../core/utils/fetch-all-page-content';

@Component({
  selector: 'app-game-form-page',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatCardModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatProgressSpinnerModule,
    MatSelectModule,
  ],
  templateUrl: './game-form-page.component.html',
  styleUrl: './game-form-page.component.scss',
})
export class GameFormPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly gameService = inject(GameService);
  private readonly genreService = inject(GenreService);
  private readonly companyService = inject(ProductionCompanyService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly cdr = inject(ChangeDetectorRef);

  readonly mode = (this.route.snapshot.data['mode'] as 'create' | 'edit') ?? 'create';
  readonly gameId = this.route.snapshot.paramMap.get('id');

  genres: Genre[] = [];
  companies: ProductionCompany[] = [];
  loading = true;
  submitError: string | null = null;
  submitting = false;

  readonly form = this.fb.group({
    title: this.fb.control<string>('', [Validators.required, Validators.maxLength(150)]),
    releaseYear: this.fb.control<number | null>(null, [Validators.required, Validators.min(1950)]),
    description: this.fb.control<string>(''),
    developerId: this.fb.control<number | null>(null),
    publisherId: this.fb.control<number | null>(null),
    genreIds: this.fb.control<number[]>([], [Validators.required]),
  });

  ngOnInit(): void {
    this.loadPageData();
  }

  private async loadPageData(): Promise<void> {
    try {
      this.loading = true;
      await this.loadReferenceData();
      if (this.mode === 'edit') {
        await this.loadGame();
      }
    } catch (error) {
      const apiError = error as ApiError;
      this.submitError = apiError?.message || 'Failed to load form data. Please try again.';
    } finally {
      this.loading = false;
      this.cdr.markForCheck();
    }
  }

  private async loadReferenceData(): Promise<void> {
    const [genresResponse, companies] = await Promise.all([
      firstValueFrom(this.genreService.getAll()),
      fetchAllPageContent((params) => this.companyService.getAll(params), {
        sortBy: 'name',
        sortDirection: 'ASC' as const,
      }),
    ]);
    this.genres = Array.isArray(genresResponse) ? genresResponse : [];
    this.companies = companies;
  }

  private async loadGame(): Promise<void> {
    if (!this.gameId) {
      throw new Error('Game id is required for edit mode.');
    }

    const game = await firstValueFrom(this.gameService.getById(this.gameId));
    this.form.patchValue({
      title: game.title || '',
      releaseYear: game.releaseYear ?? null,
      description: game.description || '',
      developerId: game.developer?.id ?? null,
      publisherId: game.publisher?.id ?? null,
      genreIds: game.genres?.map((genre) => genre.id) ?? [],
    });
  }

  get titleLabel(): string {
    return this.mode === 'edit' ? 'Edit Game' : 'Create Game';
  }

  async submit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.submitError = null;
    this.submitting = true;

    const value = this.form.getRawValue();
    const payload = {
      title: value.title?.trim() ?? '',
      releaseYear: Number(value.releaseYear),
      description: value.description?.trim() || null,
      developerId: value.developerId ?? null,
      publisherId: value.publisherId ?? null,
      genreIds: value.genreIds ?? [],
    };

    try {
      if (this.mode === 'edit') {
        if (!this.gameId) {
          throw new Error('Game id is required for update.');
        }
        const updated = await firstValueFrom(this.gameService.update(this.gameId, payload));
        this.router.navigate(['/games', updated.id]);
      } else {
        const created = await firstValueFrom(this.gameService.create(payload));
        this.router.navigate(['/games', created.id]);
      }
    } catch (error) {
      const apiError = error as ApiError;
      const validationMessage =
        apiError?.errors && typeof apiError.errors === 'object'
          ? Object.values(apiError.errors)[0]
          : null;
      this.submitError = validationMessage || apiError?.message || 'Failed to save game. Please try again.';
    } finally {
      this.submitting = false;
      this.cdr.markForCheck();
    }
  }

  cancel() {
    if (this.mode === 'edit' && this.gameId) {
      this.router.navigate(['/games', this.gameId]);
      return;
    }

    this.router.navigate(['/']);
  }

  getFieldError(fieldName: string): string | null {
    const control = this.form.get(fieldName);
    if (!control || !control.touched || !control.errors) {
      return null;
    }

    if (control.errors['required']) {
      return 'This field is required';
    }

    if (control.errors['maxlength']) {
      return `Max length is ${control.errors['maxlength'].requiredLength}`;
    }

    if (control.errors['min']) {
      return `Minimum value is ${control.errors['min'].min}`;
    }

    return 'Invalid value';
  }
}

<section class="page">
  <mat-card *ngIf="loading" class="state state-loading">
    <mat-progress-spinner mode="indeterminate"></mat-progress-spinner>
  </mat-card>

  <mat-card *ngIf="!loading" class="form-card">
    <div class="header">
      <h1>{{ titleLabel }}</h1>
      <p>Fill in the game data and save changes.</p>
    </div>

    <div *ngIf="submitError" class="error-banner">
      <mat-icon color="warn">error_outline</mat-icon>
      <span>{{ submitError }}</span>
    </div>

    <form [formGroup]="form" (ngSubmit)="submit()">
      <div class="form-grid">
        <mat-form-field appearance="outline" class="full">
          <mat-label>Title</mat-label>
          <input matInput formControlName="title" />
          <mat-error *ngIf="getFieldError('title')">{{ getFieldError('title') }}</mat-error>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Release year</mat-label>
          <input matInput type="number" min="1950" formControlName="releaseYear" />
          <mat-error *ngIf="getFieldError('releaseYear')">{{ getFieldError('releaseYear') }}</mat-error>
        </mat-form-field>

        <mat-form-field appearance="outline" class="full">
          <mat-label>Description</mat-label>
          <textarea matInput rows="4" formControlName="description"></textarea>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Developer</mat-label>
          <mat-select formControlName="developerId">
            <mat-option [value]="null">None</mat-option>
            <mat-option *ngFor="let company of companies" [value]="company.id">
              {{ company.name }}
            </mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline">
          <mat-label>Publisher</mat-label>
          <mat-select formControlName="publisherId">
            <mat-option [value]="null">None</mat-option>
            <mat-option *ngFor="let company of companies" [value]="company.id">
              {{ company.name }}
            </mat-option>
          </mat-select>
        </mat-form-field>

        <mat-form-field appearance="outline" class="full">
          <mat-label>Genres</mat-label>
          <mat-select formControlName="genreIds" multiple>
            <mat-option *ngFor="let genre of genres" [value]="genre.id">
              {{ genre.name }}
            </mat-option>
          </mat-select>
          <mat-error *ngIf="getFieldError('genreIds')">{{ getFieldError('genreIds') }}</mat-error>
        </mat-form-field>
      </div>

      <div class="actions">
        <button type="button" mat-stroked-button color="primary" (click)="cancel()" [disabled]="submitting">
          Cancel
        </button>
        <button type="submit" mat-flat-button color="primary" [disabled]="submitting">
          {{ mode === 'edit' ? 'Save changes' : 'Create game' }}
        </button>
      </div>
    </form>
  </mat-card>
</section>

// frontend-react-app/src/pages/GameFormPage.jsx
﻿import React from 'react';
import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded';
import SaveRoundedIcon from '@mui/icons-material/SaveRounded';
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  FormControl,
  FormHelperText,
  InputLabel,
  MenuItem,
  OutlinedInput,
  Paper,
  Select,
  Stack,
  TextField,
  Typography,
} from '@mui/material';
import { Controller, useForm } from 'react-hook-form';
import { Link as RouterLink, useNavigate, useParams } from 'react-router-dom';
import GameService from '../services/GameService';
import GenreService from '../services/GenreService';
import log from '../services/Logger';
import ProductionCompanyService from '../services/ProductionCompanyService';
import { fetchAllPageContent } from '../utils/fetchAllPageContent';

const DEFAULT_VALUES = {
  title: '',
  releaseYear: '',
  description: '',
  developerId: '',
  publisherId: '',
  genreIds: [],
};

const toNullableNumber = (value) => {
  if (value === '' || value === null || value === undefined) {
    return null;
  }

  const parsed = Number(value);
  return Number.isNaN(parsed) ? null : parsed;
};

function GameFormPage({ mode }) {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditMode = mode === 'edit';

  const {
    control,
    handleSubmit,
    register,
    reset,
    formState: { errors, isSubmitting },
  } = useForm({
    defaultValues: DEFAULT_VALUES,
  });

  const [genres, setGenres] = React.useState([]);
  const [companies, setCompanies] = React.useState([]);
  const [loading, setLoading] = React.useState(true);
  const [submitError, setSubmitError] = React.useState(null);

  const loadReferenceData = React.useCallback(async () => {
    const [genresResponse, companies] = await Promise.all([
      GenreService.getAll(),
      fetchAllPageContent(
        (params) => ProductionCompanyService.getAll(params),
        {
        sortBy: 'id',
        sortDirection: 'ASC',
        }
      ),
    ]);

    setGenres(Array.isArray(genresResponse.data) ? genresResponse.data : []);
    setCompanies(companies);
  }, []);

  const loadGameForEdit = React.useCallback(async () => {
    if (!isEditMode) {
      return;
    }

    if (!id) {
      throw new Error('Game id is required for edit mode.');
    }

    const response = await GameService.getById(id);
    const game = response.data;

    reset({
      title: game.title || '',
      releaseYear: game.releaseYear ?? '',
      description: game.description || '',
      developerId: game.developer?.id ?? '',
      publisherId: game.publisher?.id ?? '',
      genreIds: Array.isArray(game.genres) ? game.genres.map((genre) => genre.id) : [],
    });
  }, [id, isEditMode, reset]);

  React.useEffect(() => {
    let active = true;

    const loadPageData = async () => {
      try {
        setLoading(true);
        await loadReferenceData();
        await loadGameForEdit();
      } catch (error) {
        log.error('Failed to initialize game form:', error);
        if (active) {
          setSubmitError('Failed to load form data. Please try again.');
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    };

    loadPageData();

    return () => {
      active = false;
    };
  }, [loadGameForEdit, loadReferenceData]);

  const onSubmit = async (formValues) => {
    setSubmitError(null);

    const payload = {
      title: formValues.title.trim(),
      releaseYear: Number(formValues.releaseYear),
      description: formValues.description?.trim() || null,
      developerId: toNullableNumber(formValues.developerId),
      publisherId: toNullableNumber(formValues.publisherId),
      genreIds: formValues.genreIds || [],
    };

    try {
      if (isEditMode) {
        if (!id) {
          throw new Error('Game id is required for update.');
        }
        const updateResponse = await GameService.update(id, payload);
        navigate(`/games/${updateResponse.data.id}`);
      } else {
        const createResponse = await GameService.create(payload);
        navigate(`/games/${createResponse.data.id}`);
      }
    } catch (error) {
      log.error('Failed to submit game form:', error);

      const validationErrors = error?.errors;
      if (validationErrors && typeof validationErrors === 'object') {
        const firstValidationMessage = Object.values(validationErrors)[0];
        setSubmitError(firstValidationMessage || 'Validation failed.');
      } else {
        setSubmitError(error.message || 'Failed to save game. Please try again.');
      }
    }
  };

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" mt={10}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <Paper sx={{ p: 3 }}>
      <Stack spacing={3}>
        <Box>
          <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
            {isEditMode ? 'Edit Game' : 'Create Game'}
          </Typography>
          <Typography color="text.secondary">
            Fill in the game data and save changes.
          </Typography>
        </Box>

        {submitError && <Alert severity="error">{submitError}</Alert>}

        <Box component="form" onSubmit={handleSubmit(onSubmit)}>
          <Stack spacing={2.5}>
            <TextField
              label="Title"
              fullWidth
              error={Boolean(errors.title)}
              helperText={errors.title?.message}
              {...register('title', {
                required: 'Title is required',
                maxLength: {
                  value: 150,
                  message: 'Title must be at most 150 characters',
                },
              })}
            />

            <TextField
              label="Release year"
              type="number"
              fullWidth
              error={Boolean(errors.releaseYear)}
              helperText={errors.releaseYear?.message}
              slotProps = {{htmlInput : { min: 1950 }}}
              {...register('releaseYear', {
                required: 'Release year is required',
                valueAsNumber: true,
                min: {
                  value: 1950,
                  message: 'Release year must be at least 1950',
                },
              })}
            />

            <TextField
              label="Description"
              multiline
              minRows={4}
              fullWidth
              {...register('description')}
            />

            <Controller
              name="developerId"
              control={control}
              render={({ field }) => (
                <FormControl fullWidth>
                  <InputLabel id="developer-select-label">Developer</InputLabel>
                  <Select
                    {...field}
                    labelId="developer-select-label"
                    label="Developer"
                  >
                    <MenuItem value="">None</MenuItem>
                    {companies.map((company) => (
                      <MenuItem key={`developer-${company.id}`} value={company.id}>
                        {company.name}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              )}
            />

            <Controller
              name="publisherId"
              control={control}
              render={({ field }) => (
                <FormControl fullWidth>
                  <InputLabel id="publisher-select-label">Publisher</InputLabel>
                  <Select
                    {...field}
                    labelId="publisher-select-label"
                    label="Publisher"
                  >
                    <MenuItem value="">None</MenuItem>
                    {companies.map((company) => (
                      <MenuItem key={`publisher-${company.id}`} value={company.id}>
                        {company.name}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              )}
            />

            <Controller
              name="genreIds"
              control={control}
              rules={{
                validate: (value) =>
                  (Array.isArray(value) && value.length > 0) || 'Select at least one genre',
              }}
              render={({ field }) => (
                <FormControl fullWidth error={Boolean(errors.genreIds)}>
                  <InputLabel id="genre-multi-select-label">Genres</InputLabel>
                  <Select
                    {...field}
                    multiple
                    labelId="genre-multi-select-label"
                    label="Genres"
                    input={<OutlinedInput label="Genres" />}
                    renderValue={(selected) =>
                      selected
                        .map((genreId) => genres.find((genre) => genre.id === genreId)?.name)
                        .filter(Boolean)
                        .join(', ')
                    }
                  >
                    {genres.map((genre) => (
                      <MenuItem key={genre.id} value={genre.id}>
                        {genre.name}
                      </MenuItem>
                    ))}
                  </Select>
                  {errors.genreIds && <FormHelperText>{errors.genreIds.message}</FormHelperText>}
                </FormControl>
              )}
            />

            <Stack direction="row" spacing={1.5}>
              <Button
                component={RouterLink}
                to={isEditMode && id ? `/games/${id}` : '/'}
                variant="outlined"
                startIcon={<ArrowBackRoundedIcon />}
                disabled={isSubmitting}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                variant="contained"
                startIcon={<SaveRoundedIcon />}
                disabled={isSubmitting}
              >
                {isEditMode ? 'Save changes' : 'Create game'}
              </Button>
            </Stack>
          </Stack>
        </Box>
      </Stack>
    </Paper>
  );
}

export default GameFormPage;
