// frontend-react-app/src/pages/GamesPage.jsx
﻿import React, { useCallback, useEffect, useMemo, useState } from 'react';
import VisibilityRoundedIcon from '@mui/icons-material/VisibilityRounded';
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  Chip,
  FormControl,
  IconButton,
  InputLabel,
  MenuItem,
  OutlinedInput,
  Paper,
  Rating,
  Select,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  TableSortLabel,
  TextField,
  Typography,
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import GameService from '../services/GameService';
import GenreService from '../services/GenreService';
import ProductionCompanyService from '../services/ProductionCompanyService';
import log from '../services/Logger';
import { fetchAllPageContent } from '../utils/fetchAllPageContent';
import { normalizePageResponse } from '../utils/pageResponse';

const EMPTY_FILTERS = Object.freeze({
  title: '',
  yearFrom: '',
  yearTo: '',
  genreIds: [],
  developerId: '',
  publisherId: '',
  ratingFrom: '',
  ratingTo: '',
});

const buildFilterParams = (filters, pagingAndSorting) => ({
  ...pagingAndSorting,
  title: filters.title || undefined,
  yearFrom: filters.yearFrom ? Number(filters.yearFrom) : undefined,
  yearTo: filters.yearTo ? Number(filters.yearTo) : undefined,
  genreIds: filters.genreIds.length ? filters.genreIds.join(',') : undefined,
  developerId: filters.developerId ? Number(filters.developerId) : undefined,
  publisherId: filters.publisherId ? Number(filters.publisherId) : undefined,
  ratingFrom: filters.ratingFrom ? Number(filters.ratingFrom) : undefined,
  ratingTo: filters.ratingTo ? Number(filters.ratingTo) : undefined,
});

const GamesPage = () => {
  const navigate = useNavigate();

  const [games, setGames] = useState([]);
  const [genres, setGenres] = useState([]);
  const [companies, setCompanies] = useState([]);
  const [totalElements, setTotalElements] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const [sortBy, setSortBy] = useState('id');
  const [sortDirection, setSortDirection] = useState('ASC');

  const [filters, setFilters] = useState(EMPTY_FILTERS);
  const [appliedFilters, setAppliedFilters] = useState(EMPTY_FILTERS);

  const columns = useMemo(
    () => [
      { key: 'id', label: 'ID', sortable: true },
      { key: 'title', label: 'Title', sortable: true },
      { key: 'releaseYear', label: 'Release Year', sortable: true },
      { key: 'genres', label: 'Genres', sortable: false },
      { key: 'developerName', label: 'Developer', sortable: false },
      { key: 'publisherName', label: 'Publisher', sortable: false },
      { key: 'averageRating', label: 'Rating', sortable: true, sortField: 'averageRating' },
      { key: 'actions', label: 'Actions', sortable: false },
    ],
    []
  );

  const hasActiveFilters = useMemo(
    () =>
      Boolean(
        appliedFilters.title ||
          appliedFilters.yearFrom ||
          appliedFilters.yearTo ||
          appliedFilters.genreIds.length ||
          appliedFilters.developerId ||
          appliedFilters.publisherId ||
          appliedFilters.ratingFrom ||
          appliedFilters.ratingTo
      ),
    [appliedFilters]
  );

  const fetchGenres = useCallback(async () => {
    try {
      const response = await GenreService.getAll();
      setGenres(Array.isArray(response.data) ? response.data : []);
    } catch (err) {
      log.warn('Failed to load genres for filters:', err);
    }
  }, []);

  const fetchCompanies = useCallback(async () => {
    try {
      const allCompanies = await fetchAllPageContent(
        (params) => ProductionCompanyService.getAll(params),
        {
          sortBy: 'name',
          sortDirection: 'ASC',
        }
      );
      setCompanies(allCompanies);
    } catch (err) {
      log.warn('Failed to load companies for filters:', err);
    }
  }, []);

  const fetchGames = useCallback(async () => {
    try {
      setLoading(true);

      const pagingAndSorting = {
        page,
        size: pageSize,
        sortBy,
        sortDirection,
      };

      const response = hasActiveFilters
        ? await GameService.filter(buildFilterParams(appliedFilters, pagingAndSorting))
        : await GameService.getAll(pagingAndSorting);

      const pageData = normalizePageResponse(response.data);

      setGames(pageData.content);
      setTotalElements(pageData.totalElements);
      setError(null);
    } catch (err) {
      log.error('Error fetching games:', err);
      setError('Failed to load game list. Check backend connection and try again.');
    } finally {
      setLoading(false);
    }
  }, [appliedFilters, hasActiveFilters, page, pageSize, sortBy, sortDirection]);

  useEffect(() => {
    fetchGenres();
    fetchCompanies();
  }, [fetchGenres, fetchCompanies]);

  useEffect(() => {
    fetchGames();
  }, [fetchGames]);

  const handleSort = (field) => {
    if (!field) {
      return;
    }

    if (sortBy === field) {
      setSortDirection((prev) => (prev === 'ASC' ? 'DESC' : 'ASC'));
    } else {
      setSortBy(field);
      setSortDirection('ASC');
    }

    setPage(0);
  };

  const handleChangePage = (_event, newPage) => {
    setPage(newPage);
  };

  const handleChangePageSize = (event) => {
    const newPageSize = Number(event.target.value);
    setPageSize(newPageSize);
    setPage(0);
  };

  const handleTextFilterChange = (field) => (event) => {
    setFilters((prev) => ({ ...prev, [field]: event.target.value }));
  };

  const handleSelectFilterChange = (field) => (event) => {
    setFilters((prev) => ({ ...prev, [field]: event.target.value }));
  };

  const handleGenreChange = (event) => {
    const value = event.target.value;
    const genreIds = (Array.isArray(value) ? value : value.split(',')).map(Number);
    setFilters((prev) => ({ ...prev, genreIds }));
  };

  const applyFilters = () => {
    setAppliedFilters({
      title: filters.title.trim(),
      yearFrom: filters.yearFrom,
      yearTo: filters.yearTo,
      genreIds: filters.genreIds,
      developerId: filters.developerId,
      publisherId: filters.publisherId,
      ratingFrom: filters.ratingFrom,
      ratingTo: filters.ratingTo,
    });
    setPage(0);
  };

  const resetFilters = () => {
    const resetValue = {
      ...EMPTY_FILTERS,
      genreIds: [],
    };
    setFilters(resetValue);
    setAppliedFilters(resetValue);
    setPage(0);
  };

  if (loading && games.length === 0) {
    return (
      <Box display="flex" justifyContent="center" mt={10}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return (
      <Stack spacing={2}>
        <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
          Games
        </Typography>
        <Alert severity="error">{error}</Alert>
        <Box>
          <Button variant="contained" onClick={fetchGames}>
            Retry
          </Button>
        </Box>
      </Stack>
    );
  }

  return (
    <Stack spacing={2}>
      <Typography variant="h4" component="h1" sx={{ fontWeight: 700 }}>
        Games
      </Typography>

      <Paper sx={{ p: 2 }}>
        <Stack spacing={2}>
          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
            <TextField
              label="Search title"
              value={filters.title}
              onChange={handleTextFilterChange('title')}
              fullWidth
            />

            <TextField
              label="Year from"
              type="number"
              value={filters.yearFrom}
              onChange={handleTextFilterChange('yearFrom')}
              slotProps={{ htmlInput: { min: 1950 } }}
              sx={{ minWidth: 140 }}
            />

            <TextField
              label="Year to"
              type="number"
              value={filters.yearTo}
              onChange={handleTextFilterChange('yearTo')}
              slotProps={{ htmlInput: { min: 1950 } }}
              sx={{ minWidth: 140 }}
            />

            <FormControl sx={{ minWidth: 240 }}>
              <InputLabel id="genres-filter-label">Genres</InputLabel>
              <Select
                labelId="genres-filter-label"
                id="genres-filter"
                multiple
                value={filters.genreIds}
                onChange={handleGenreChange}
                input={<OutlinedInput label="Genres" />}
                renderValue={(selected) =>
                  selected
                    .map((id) => genres.find((genre) => genre.id === id)?.name)
                    .filter(Boolean)
                    .join(', ')
                }
              >
                {genres.map((genre) => (
                  <MenuItem key={genre.id} value={genre.id}>
                    {genre.name}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          </Stack>

          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} alignItems={{ md: 'flex-end' }}>
            <FormControl sx={{ minWidth: 240 }}>
              <InputLabel id="developer-filter-label">Developer</InputLabel>
              <Select
                labelId="developer-filter-label"
                label="Developer"
                value={filters.developerId}
                onChange={handleSelectFilterChange('developerId')}
              >
                <MenuItem value="">All</MenuItem>
                {companies.map((company) => (
                  <MenuItem key={`dev-${company.id}`} value={company.id}>
                    {company.name}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            <FormControl sx={{ minWidth: 240 }}>
              <InputLabel id="publisher-filter-label">Publisher</InputLabel>
              <Select
                labelId="publisher-filter-label"
                label="Publisher"
                value={filters.publisherId}
                onChange={handleSelectFilterChange('publisherId')}
              >
                <MenuItem value="">All</MenuItem>
                {companies.map((company) => (
                  <MenuItem key={`pub-${company.id}`} value={company.id}>
                    {company.name}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>

            <TextField
              label="Rating from"
              type="number"
              value={filters.ratingFrom}
              onChange={handleTextFilterChange('ratingFrom')}
              inputProps={{ min: 0, max: 100 }}
              sx={{ minWidth: 140 }}
            />

            <TextField
              label="Rating to"
              type="number"
              value={filters.ratingTo}
              onChange={handleTextFilterChange('ratingTo')}
              inputProps={{ min: 0, max: 100 }}
              sx={{ minWidth: 140 }}
            />

            <Button variant="contained" onClick={applyFilters}>
              Apply
            </Button>

            <Button variant="outlined" onClick={resetFilters}>
              Reset
            </Button>
          </Stack>
        </Stack>
      </Paper>

      {games.length === 0 ? (
        <Alert severity="info">No games found.</Alert>
      ) : (
        <TableContainer component={Paper} elevation={3}>
          <Table sx={{ minWidth: 650 }} aria-label="games table">
            <TableHead sx={{ backgroundColor: '#f5f5f5' }}>
              <TableRow>
                {columns.map((column) => (
                  <TableCell key={column.key}>
                    {column.sortable ? (
                      <TableSortLabel
                        active={sortBy === (column.sortField || column.key)}
                        direction={sortBy === (column.sortField || column.key) ? sortDirection.toLowerCase() : 'asc'}
                        onClick={() => handleSort(column.sortField || column.key)}
                      >
                        <strong>{column.label}</strong>
                      </TableSortLabel>
                    ) : (
                      <strong>{column.label}</strong>
                    )}
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {games.map((game) => (
                <TableRow
                  key={game.id}
                  hover
                  onClick={() => navigate(`/games/${game.id}`)}
                  sx={{
                    '&:last-child td, &:last-child th': { border: 0 },
                    cursor: 'pointer',
                  }}
                >
                  <TableCell component="th" scope="row">
                    {game.id}
                  </TableCell>

                  <TableCell>{game.title}</TableCell>

                  <TableCell>{game.releaseYear}</TableCell>

                  <TableCell>
                    {game.genreNames?.map((genre) => (
                      <Chip
                        key={`${game.id}-${genre}`}
                        label={genre}
                        size="small"
                        variant="outlined"
                        sx={{ mr: 0.5, mb: 0.5 }}
                      />
                    ))}
                  </TableCell>

                  <TableCell>{game.developerName || '-'}</TableCell>

                  <TableCell>{game.publisherName || '-'}</TableCell>

                  <TableCell>
                    <Box display="flex" alignItems="center">
                      {game.averageRating !== null && game.averageRating !== undefined ? (
                        <>
                          <Rating value={game.averageRating / 20} readOnly precision={0.5} size="small" />
                          <Typography variant="body2" color="text.secondary" ml={1}>
                            {Math.round(game.averageRating)}
                          </Typography>
                        </>
                      ) : (
                        <Typography variant="caption" color="text.secondary">
                          N/A
                        </Typography>
                      )}
                    </Box>
                  </TableCell>

                  <TableCell onClick={(event) => event.stopPropagation()}>
                    <IconButton aria-label={`open game ${game.title}`} onClick={() => navigate(`/games/${game.id}`)}>
                      <VisibilityRoundedIcon />
                    </IconButton>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          <TablePagination
            component="div"
            count={totalElements}
            page={page}
            onPageChange={handleChangePage}
            rowsPerPage={pageSize}
            onRowsPerPageChange={handleChangePageSize}
            rowsPerPageOptions={[1, 5, 10, 20, 50]}
          />
        </TableContainer>
      )}
    </Stack>
  );
};

export default GamesPage;

// frontend-angular-app/src/app/pages/games-page/games-page.component.ts
import { CommonModule } from '@angular/common';
import { Component, DestroyRef, OnInit, ViewChild, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatPaginator, MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatSelectModule } from '@angular/material/select';
import { MatSort, MatSortModule, Sort } from '@angular/material/sort';
import { MatTableModule } from '@angular/material/table';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { firstValueFrom } from 'rxjs';
import { ApiError } from '../../core/http/api-error';
import { GameService } from '../../core/services/game.service';
import { GenreService } from '../../core/services/genre.service';
import { ProductionCompanyService } from '../../core/services/production-company.service';
import { fetchAllPageContent } from '../../core/utils/fetch-all-page-content';
import { normalizePageResponse } from '../../core/utils/normalize-page-response';
import { GameListItem } from '../../core/models/game';
import { Genre } from '../../core/models/genre';
import { ProductionCompany } from '../../core/models/production-company';
import { GameFilterParams, SortDirection } from '../../core/models/query-params';

@Component({
  selector: 'app-games-page',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatCardModule,
    MatChipsModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatPaginatorModule,
    MatSelectModule,
    MatSortModule,
    MatTableModule,
    MatProgressSpinnerModule,
    FormsModule,
  ],
  templateUrl: './games-page.component.html',
  styleUrl: './games-page.component.scss',
})
export class GamesPageComponent implements OnInit {
  private readonly gameService = inject(GameService);
  private readonly genreService = inject(GenreService);
  private readonly companyService = inject(ProductionCompanyService);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  @ViewChild(MatPaginator) paginator?: MatPaginator;
  @ViewChild(MatSort) sort?: MatSort;

  readonly displayedColumns = [
    'id',
    'title',
    'releaseYear',
    'genres',
    'developerName',
    'publisherName',
    'averageRating',
    'actions',
  ];

  games: GameListItem[] = [];
  genres: Genre[] = [];
  companies: ProductionCompany[] = [];
  totalElements = 0;
  loading = true;
  error: string | null = null;

  page = 0;
  pageSize = 10;
  sortBy = 'id';
  sortDirection: SortDirection = 'ASC';

  filters = {
    title: '',
    yearFrom: '',
    yearTo: '',
    genreIds: [] as number[],
    developerId: '',
    publisherId: '',
    ratingFrom: '',
    ratingTo: '',
  };

  appliedFilters = {
    title: '',
    yearFrom: '',
    yearTo: '',
    genreIds: [] as number[],
    developerId: '',
    publisherId: '',
    ratingFrom: '',
    ratingTo: '',
  };

  ngOnInit(): void {
    this.loadFiltersData();
    this.fetchGames();
  }

  async loadFiltersData() {
    try {
      const [genresResponse, companies] = await Promise.all([
        firstValueFrom(this.genreService.getAll()),
        fetchAllPageContent((params) => this.companyService.getAll(params), {
          sortBy: 'name',
          sortDirection: 'ASC' as const,
        }),
      ]);
      this.genres = Array.isArray(genresResponse) ? genresResponse : [];
      this.companies = companies;
    } catch {
      // ignore filter data errors for now
    }
  }

  private buildFilterParams(): GameFilterParams {
    return {
      page: this.page,
      size: this.pageSize,
      sortBy: this.sortBy,
      sortDirection: this.sortDirection,
      title: this.appliedFilters.title || undefined,
      yearFrom: this.appliedFilters.yearFrom ? Number(this.appliedFilters.yearFrom) : undefined,
      yearTo: this.appliedFilters.yearTo ? Number(this.appliedFilters.yearTo) : undefined,
      genreIds: this.appliedFilters.genreIds.length
        ? this.appliedFilters.genreIds.join(',')
        : undefined,
      developerId: this.appliedFilters.developerId
        ? Number(this.appliedFilters.developerId)
        : undefined,
      publisherId: this.appliedFilters.publisherId
        ? Number(this.appliedFilters.publisherId)
        : undefined,
      ratingFrom: this.appliedFilters.ratingFrom
        ? Number(this.appliedFilters.ratingFrom)
        : undefined,
      ratingTo: this.appliedFilters.ratingTo ? Number(this.appliedFilters.ratingTo) : undefined,
    };
  }

  get hasActiveFilters(): boolean {
    return Boolean(
      this.appliedFilters.title ||
        this.appliedFilters.yearFrom ||
        this.appliedFilters.yearTo ||
        this.appliedFilters.genreIds.length ||
        this.appliedFilters.developerId ||
        this.appliedFilters.publisherId ||
        this.appliedFilters.ratingFrom ||
        this.appliedFilters.ratingTo
    );
  }

  fetchGames() {
    this.loading = true;
    this.error = null;

    const request$ = this.hasActiveFilters
      ? this.gameService.filter(this.buildFilterParams())
      : this.gameService.getAll({
          page: this.page,
          size: this.pageSize,
          sortBy: this.sortBy,
          sortDirection: this.sortDirection,
        });

    request$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (response) => {
        const page = normalizePageResponse(response);
        this.games = page.content;
        this.totalElements = page.totalElements;
        this.loading = false;
      },
      error: (err: unknown) => {
        const apiError = err as ApiError;
        this.error = apiError?.message || 'Failed to load game list. Check backend connection and try again.';
        this.loading = false;
      },
    });
  }

  applyFilters() {
    this.appliedFilters = {
      title: this.filters.title.trim(),
      yearFrom: this.filters.yearFrom,
      yearTo: this.filters.yearTo,
      genreIds: [...this.filters.genreIds],
      developerId: this.filters.developerId,
      publisherId: this.filters.publisherId,
      ratingFrom: this.filters.ratingFrom,
      ratingTo: this.filters.ratingTo,
    };
    this.page = 0;
    this.fetchGames();
  }

  resetFilters() {
    this.filters = {
      title: '',
      yearFrom: '',
      yearTo: '',
      genreIds: [],
      developerId: '',
      publisherId: '',
      ratingFrom: '',
      ratingTo: '',
    };
    this.appliedFilters = { ...this.filters, genreIds: [] };
    this.page = 0;
    this.fetchGames();
  }

  onSortChange(sort: Sort) {
    if (!sort.active || !sort.direction) {
      return;
    }

    this.sortBy = sort.active;
    this.sortDirection = sort.direction === 'asc' ? 'ASC' : 'DESC';
    this.page = 0;
    this.fetchGames();
  }

  onPageChange(event: PageEvent) {
    this.page = event.pageIndex;
    this.pageSize = event.pageSize;
    this.fetchGames();
  }

  navigateToGame(id: number) {
    this.router.navigate(['/games', id]);
  }

  getGenreName(id: number): string {
    return this.genres.find((genre) => genre.id === id)?.name ?? '';
  }
}

<section class="page">
  <div class="page-header">
    <h1>Games</h1>
  </div>

  <mat-card class="filters-card">
    <div class="filters-grid">
      <mat-form-field appearance="outline" class="full">
        <mat-label>Search title</mat-label>
        <input matInput [(ngModel)]="filters.title" />
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Year from</mat-label>
        <input matInput type="number" min="1950" [(ngModel)]="filters.yearFrom" />
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Year to</mat-label>
        <input matInput type="number" min="1950" [(ngModel)]="filters.yearTo" />
      </mat-form-field>

      <mat-form-field appearance="outline" class="full">
        <mat-label>Genres</mat-label>
        <mat-select multiple [(ngModel)]="filters.genreIds">
          <mat-option *ngFor="let genre of genres" [value]="genre.id">
            {{ genre.name }}
          </mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Developer</mat-label>
        <mat-select [(ngModel)]="filters.developerId">
          <mat-option value="">All</mat-option>
          <mat-option *ngFor="let company of companies" [value]="company.id">
            {{ company.name }}
          </mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Publisher</mat-label>
        <mat-select [(ngModel)]="filters.publisherId">
          <mat-option value="">All</mat-option>
          <mat-option *ngFor="let company of companies" [value]="company.id">
            {{ company.name }}
          </mat-option>
        </mat-select>
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Rating from</mat-label>
        <input matInput type="number" min="0" max="100" [(ngModel)]="filters.ratingFrom" />
      </mat-form-field>

      <mat-form-field appearance="outline">
        <mat-label>Rating to</mat-label>
        <input matInput type="number" min="0" max="100" [(ngModel)]="filters.ratingTo" />
      </mat-form-field>

      <div class="filters-actions">
        <button mat-flat-button color="primary" (click)="applyFilters()">Apply</button>
        <button mat-stroked-button color="primary" (click)="resetFilters()">Reset</button>
      </div>
    </div>
  </mat-card>

  <div *ngIf="loading && games.length === 0" class="state state-loading">
    <mat-progress-spinner mode="indeterminate"></mat-progress-spinner>
  </div>

  <mat-card *ngIf="error" class="state state-error">
    <div class="state-row">
      <mat-icon color="warn">error_outline</mat-icon>
      <span>{{ error }}</span>
    </div>
    <button mat-flat-button color="primary" (click)="fetchGames()">Retry</button>
  </mat-card>

  <mat-card *ngIf="!loading && !error && games.length === 0" class="state state-empty">
    <div class="state-row">
      <mat-icon>info</mat-icon>
      <span>No games found.</span>
    </div>
  </mat-card>

  <mat-card *ngIf="!error && games.length > 0" class="table-card">
    <table mat-table [dataSource]="games" matSort (matSortChange)="onSortChange($event)">
      <ng-container matColumnDef="id">
        <th mat-header-cell *matHeaderCellDef mat-sort-header="id">ID</th>
        <td mat-cell *matCellDef="let game">{{ game.id }}</td>
      </ng-container>

      <ng-container matColumnDef="title">
        <th mat-header-cell *matHeaderCellDef mat-sort-header="title">Title</th>
        <td mat-cell *matCellDef="let game">{{ game.title }}</td>
      </ng-container>

      <ng-container matColumnDef="releaseYear">
        <th mat-header-cell *matHeaderCellDef mat-sort-header="releaseYear">Release Year</th>
        <td mat-cell *matCellDef="let game">{{ game.releaseYear || '-' }}</td>
      </ng-container>

      <ng-container matColumnDef="genres">
        <th mat-header-cell *matHeaderCellDef>Genres</th>
        <td mat-cell *matCellDef="let game">
          <mat-chip-set *ngIf="game.genreNames?.length; else noGenres" class="chip-set">
            <mat-chip *ngFor="let name of game.genreNames" color="primary" variant="outlined">
              {{ name }}
            </mat-chip>
          </mat-chip-set>
          <ng-template #noGenres>-</ng-template>
        </td>
      </ng-container>

      <ng-container matColumnDef="developerName">
        <th mat-header-cell *matHeaderCellDef>Developer</th>
        <td mat-cell *matCellDef="let game">{{ game.developerName || '-' }}</td>
      </ng-container>

      <ng-container matColumnDef="publisherName">
        <th mat-header-cell *matHeaderCellDef>Publisher</th>
        <td mat-cell *matCellDef="let game">{{ game.publisherName || '-' }}</td>
      </ng-container>

      <ng-container matColumnDef="averageRating">
        <th mat-header-cell *matHeaderCellDef mat-sort-header="averageRating">Rating</th>
        <td mat-cell *matCellDef="let game">
          <span *ngIf="game.averageRating !== null && game.averageRating !== undefined; else noRating">
            {{ game.averageRating | number: '1.0-0' }}
          </span>
          <ng-template #noRating> N/A </ng-template>
        </td>
      </ng-container>

      <ng-container matColumnDef="actions">
        <th mat-header-cell *matHeaderCellDef>Actions</th>
        <td mat-cell *matCellDef="let game">
          <button mat-icon-button (click)="$event.stopPropagation(); navigateToGame(game.id)">
            <mat-icon>visibility</mat-icon>
          </button>
        </td>
      </ng-container>

      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr
        mat-row
        *matRowDef="let row; columns: displayedColumns"
        class="table-row"
        (click)="navigateToGame(row.id)"
      ></tr>
    </table>

    <mat-paginator
      [length]="totalElements"
      [pageIndex]="page"
      [pageSize]="pageSize"
      [pageSizeOptions]="[1, 5, 10, 20, 50]"
      (page)="onPageChange($event)"
    ></mat-paginator>
  </mat-card>
</section>
